### ISSUE TITLE
Imported File cant also import

### ISSUE THREAD

**Issue by TagoDR** [radarsu/ts-import#18]
Hello,
After updating it doesnt seem to allow chained imports.

Load and LoadSync in Version 3.0.0-beta.3

I can import a ts file just fine, however if the file imports something else inside it, it ends in error.

```console
Error: Cannot find module '../core/data'
Require stack:
- C:\[...]\node_modules\ts-import\cache\[...]\src\utils\metadata.js
- C:\[...]\node_modules\ts-import\dist\main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\[...]\node_modules\ts-import\cache\[...]\src\utils\metadata.js:4:15)<------
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)

Process finished with exit code 1
```
Omited part [...] is path to project folder
Pointing directly to the omited index.js doesn't change the result

the arrow line links to the transpiled file at the import line
```js
var data_1 = require("../core/data");
```
Side note: if I just import but dont use the imported value it does not error out.
PS: code executed through gulpfile.js in a module type project

**Comment by radarsu** [comment]
I've released 4.0.0-beta.1 version which supports 2 modes: "transpile" and "compile". Transpile is faster, but it won't work for your use case, therefore you should use compile.

```ts
import * as tsImport from 'ts-import';

tsImport.load(`./script.ts`, {
    mode: tsImport.LoadMode.Compile,
});
```

**Comment by TagoDR** [comment]
Unfortunately, it still gives the same error, word for word, with both options set.
When I look in the cache folder, it is not pulling the 'required' files to compile/transpile them, the targeted one is alone.
Tried with 'load' and 'loadSync'.

It worked in 2.0.40 I just needed to clear the cache, now and then.

EDIT:I now see the files were compiled in place not at the cache, that may be the problem

**Comment by radarsu** [comment]
Would you be able to provide simpe repo with problem reproduction?

**Comment by TagoDR** [comment]
https://github.com/TagoDR/MangaOnlineViewer/tree/typescript

Observe the gulpfile.js line 134 using ts-import, command "npm run experiment" is set up for your convenience
I'm converting my repo to TypeScript, I used to import js files directly, now ts-import is requited.
Simple explanation: I need to import a file inside my project to extract metadata in json format to generate the userscript header and the readme.md. The data is scraped from all files ins src/main and compiled to json in src/meta-main.ts

In the previous commit, I was using version 2.0.40 and it worked, with the reference to my types, I just need to clear the cache before building.

**Comment by radarsu** [comment]
Thanks for the repo. I've checked it out and although it worked on Linux which I'm mainly testing, in beta version I still needed to account for some Windows paths handling. That should be resolved by `4.0.0-beta.2`. I'm closing an issue, but let me know if that's 100% resolved for your use-case.

**Comment by agnoam** [comment]
I have tried to use the `4.0.0-beta.6` version
And the exception still occurring.

I have tried it on *Windows 10* environment.

The code:
```
tsImport.load(`C:\\MyProject\\src\\test.ts`, {
    mode: tsImport.LoadMode.Compile
})
```

The output exception is the same as @TagoDR 's.
